name: mayaExampleCI

on:
  push:
    branches_ignore:
      - master

jobs:
  maya2019:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Unittests
        uses: docker://mottosso/maya:2019
        env:
          PUZZLE_REPO_PATH: /github/workspace/src
          PUZZLE_TASK_PATH: /github/workspace/tests/tasks
          TEMP: /github/workspace/tests
        with:
          args: /usr/autodesk/maya/bin/mayapy -m unittest discover -s ./tests/src/win -v

  maya2020:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Unittests
        uses: docker://mottosso/maya:2020
        env:
          PUZZLE_REPO_PATH: /github/workspace/src
          PUZZLE_TASK_PATH: /github/workspace/tests/tasks
          TEMP: /github/workspace/tests
        with:
          args: /usr/autodesk/maya/bin/mayapy -m unittest discover -s ./tests/src/win -v

  maya2022:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Unittests
        uses: docker://mottosso/maya:2022
        env:
          PUZZLE_REPO_PATH: /github/workspace/src
          PUZZLE_TASK_PATH: /github/workspace/tests/tasks
          TEMP: /github/workspace/tests
        with:
          args: /usr/autodesk/maya/bin/mayapy -m unittest discover -s ./tests/src/win -v
