name: mayaCI

on:
  push:
    branches-ignore:
      - main

jobs:
  tests:
    runs-on: ${{matrix.os}}
    timeout-minutes: 15
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ["2.7", "3.7", "3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run unittests
        env:
          PYTHONPATH: ${{ github.workspace }}/src      
        run: |
          python -m unittest discover -s ./tests/src/win