name: mayaCI

on:
  push:
    branches_ignore:
      - master

jobs:
  maya2019:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: set env
        run: |
          echo "PYTHONPATH=/github/workspace/src" >> $GITHUB_ENV

      - name: Run Unittests
        uses: docker://mottosso/maya:2019
        env:
          
          TEMP: /github/workspace/tests
        with:
          args: /usr/autodesk/maya/bin/mayapy -m unittest discover -s ./tests/src/win -v

  maya2020:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: set env
        run: |
          echo "PYTHONPATH=/github/workspace/src" >> $GITHUB_ENV

      - name: Run Unittests
        uses: docker://mottosso/maya:2020
        env:
          TEMP: /github/workspace/tests
        with:
          args: /usr/autodesk/maya/bin/mayapy -m unittest discover -s ./tests/src/win -v

  maya2022:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: set env
        run: |
          echo "PYTHONPATH=/github/workspace/src" >> $GITHUB_ENV

      - name: Run Unittests
        uses: docker://mottosso/maya:2022
        env:
          TEMP: /github/workspace/tests
        with:
          args: /usr/autodesk/maya/bin/mayapy -m unittest discover -s ./tests/src/win -v
