name: mayaCI

on:
  push:
    branches_ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        maya-version: 
          - 2019
          - 2020
          - 2022

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: set env
        run: |
          echo "PYTHONPATH=/github/workspace/src" >> $GITHUB_ENV

      - name: Run Unittests
        uses: docker://mottosso/maya:${{ matrix.maya-version }}
        env:
          TEMP: /github/workspace/tests
        with:
          args: /usr/autodesk/maya/bin/mayapy -m unittest discover -s ./tests/src/win -v
